language: python

python:
  - '3.6'

install:
  - pip install -r ./requirements/base.txt
  - pip install .

script: 'python --version'

deploy:
  provider: pypi
  user: 'VesnaBrucoms'
  password:
    secure: "JAiOntCqsBtDhV0bjF5lbVXCyP/6KO4Iga5F5tRwCjAL0o6T0jYVU2++QkimuY3UK1rncEWqfbz+RlRFbMkx+NbAFkaSLYCmb6BmUsYfeQB2eFkTO7aOwJ5WCHpv3Qh5x41lNp8JyN7PxlAAtzwm6MUOl/KK/Uoz6CLG8Vft4x1UB9fk1Y/ShHzGtLPaIMtWg/vhDTg6ANbWeLRlmD70q4QHbvHS2khYER8YOpgdDIXszqypbi7Fz5CSw2W4gBW5r+XPaJj9VY1m+uJ90GNg4qUqnze1mUVLGwv/dUJxRH+go3Waqjm/jpBljOmpY4C5Juc2iBz4w3Y9gegK4Ah1wvWiDZ3x/A1bChQTRsInwE7MGocskbCTon0hQPAcz93ZgBqA8sFYlJeB1/p63q4kj0RLlnGO0tpGeskA1evu/m5Uu93wF615MK3rBDodQQ0pOxjGiHOcp0uNko1pMP6S7zNCpXJzCvvp6kEsLr8ElkImh1yTWydVTs/HyPk64WoCrmOTL6l6OTuSB9SeyV597P85/k0aFqDDm2a1xga6OkfHbN2TPGxfSV4hXLzBrY3Qcz8eljFhk2Z2fYbM75MnB5rePtd6HqwHBGc8URMxbxhM3ukpRoEUjtAX6RWAe3hDJm+Z3Lx+EbQAu5nlgaS2YqAFAZ1ywYkrCQHF0P0Bq7U="
  on:
    branch: more-travis-integration
