language: python

python:
  - '3.6'

install:
  - pip install -r ./requirements/base.txt
  - pip install .

script: 'python --version'

deploy:
  provider: pypi
  user: 'VesnaBrucoms'
  password:
    secure: "iAIFL4FO6CwESS/M85yE4bCatIxyk2f++0ehz1IseMIYG5fqNCo+JL5ImIQFIj37VpfWKhmJgXzmZz76xg6EfqGPcbME2e08vL1wHO5yHuHeH/yZS62TSpCNcxeB2s5Xt0BoC8/ac3B3DfKSuilUpXH2G/je07mplBJ8rKljU6VqA1WSBRdsY4ofXfPbOb9eS7l5S30UK25/EG33jx3ZAdcldpY0uKOOYcaleI2dcfwNtH8iDkSgBchdni6PCO9nIdPI8qO4u9GPgYENfngbQAsF6JfFFkUBySfYMpPsu5zn53lTj9kcAdbjQWdyCkFxi8p0slKqUsNV2Qinn+2vqK2DzlcAPMUjwS2Snkki0EXW1g/XP7uW7yeAcr0I06cifzuIpwB8hI4r5T65nK0nM0tJRKw0uRIWlBI8ZwL9WtD+eWkAZPC5XKYL15O7/SQAv9tFdKYSvqOaf4J1McaECAh69O7N+JQrWK9nSypklClsPEM2I29TCJ4w+lZUdvVYdBwjEg6snepRirotyY9cxTglmq6TRkbadsk33CqQlx7L6Tnza9mk8PM10xDvZQw/8NOiGqG9ZdrPHH9sT5aUj7UR9JTvdAg8lU08Y36UjWmAHqLm4Jmb8hfMnLYfvErf2fdMuhj1f803YmyI96qEuwo7ZRwVf7va65UD77LDaqo="
